sudo: false
language: ruby
cache: bundler
rvm:
- jruby
jdk: oraclejdk9
script:
- bundle exec rspec spec
deploy:
  provider: rubygems
  on:
    tags: true
  gem: logstash-filter-rediss
  api_key:
    secure: jF1Lm6qHpAbrMmJiCKJd99Z3VGBZmx4gk+UKzGRgh3gkESCwNz8+TW2zEeqIwlMFBhYavO2001IVIzcnQ7WPY5tNe7OpBZlcu/lxVnz7QfZuyOHyR3QnBushX66xU3ytt+LTh4/eUUCabb9ufktSscSMCUzTqv4yapKKVLEdQaPaE2eO8VUW1m07CT4uk+HNyavAG7zHRO9h5rBscGf7n7fDxw/CfehKsO0MckTndmfClm72po4DvqJicOa+hsif2z67TZ5JWBhWXOtYKFWA8ksUHEMUFTZCrimn2ig1d1TQXDDopY6DhtVwIogmOgg7j/nGGW2GDYNWJNsGj0LKimUwsN/U96Clcvuu5d6/77CUg/ZavGyU/vpfPQ3cXBCHGcFxFo88nq+8A+dkabLvSFhHIVdnaUm8czvg+TA/He9URNkS7woRwEf6VArH6IoRQSOc6pWPllKUmwDnhJ72OAbo+p7DZj77pbWE3mRKIBuLSpWYssSHka1uzaicoj0zIthp69WhuwdOAJwISVKYebO/4nhhfaee1IKyBZP4vQ7fzrD0aD9Zxup3twOhuWSdWLa2mwGy6UDQdrlu1Mwp2IDFvqGyVUzk9hWEMT6nUakso1UkRHByVy1P6LjQW7l1FGEPt4oTwX/3w80GtZG+zSNJ77sh2HIt7pMui8Hx1GY=
